'use client';

import React, { useState, useEffect, useRef, useCallback } from 'react';

const TOOLS = [
  { id: 'multimeter', icon: '⚡', label: 'Multimeter', label_vn: 'Đồng hồ đo' },
  { id: 'screwdriver', icon: '🔧', label: 'Screwdriver', label_vn: 'Tua vít' },
  { id: 'compressed_air', icon: '💨', label: 'Compressed Air', label_vn: 'Bình xịt khí' },
  { id: 'spare_psu', icon: '🔌', label: 'Spare PSU', label_vn: 'Nguồn dự phòng' },
  { id: 'bios_speaker', icon: '🔊', label: 'BIOS Speaker', label_vn: 'Loa BIOS' },
];

const SCENARIOS = [
  {
    id: 'no_power',
    title: 'No Power',
    title_vn: 'Không Lên Nguồn',
    description: 'PC doesn\'t turn on when pressing the power button.',
    description_vn: 'PC không lên khi bấm nút nguồn.',
    symptoms: ['No fan spin', 'No LEDs', 'Power button does nothing'],
    symptoms_vn: ['Quạt không quay', 'Đèn không sáng', 'Nút nguồn không tác dụng'],
    correct_answer: 'psu',
    hints: ['Check PSU switch', 'Check power cable', 'Try different outlet', 'PSU may be dead'],
    hints_vn: ['Kiểm tra công tắc PSU', 'Kiểm tra dây nguồn', 'Thử ổ cắm khác', 'PSU có thể bị hỏng'],
    difficulty: 'easy',
    icon: '🔌',
    options: [
      { id: 'psu', label: 'Dead PSU', label_vn: 'Nguồn chết', correct: true },
      { id: 'cpu', label: 'CPU fried', label_vn: 'CPU cháy' },
      { id: 'ram', label: 'Loose RAM', label_vn: 'RAM lỏng' },
      { id: 'case', label: 'Case short circuit', label_vn: 'Case bị chập' },
    ],
    tool_hints: {
      multimeter: 'PSU voltage rails read 0V on all lines.',
      multimeter_vn: 'Các đường điện PSU đều 0V.',
      screwdriver: 'All components seated. Power header fine.',
      screwdriver_vn: 'Linh kiện gắn chặt. Đầu nối nguồn bình thường.',
      compressed_air: 'No significant dust buildup.',
      compressed_air_vn: 'Không có bụi bẩn đáng kể.',
      spare_psu: 'PC boots normally with known-good PSU.',
      spare_psu_vn: 'PC chạy bình thường với nguồn khác.',
      bios_speaker: 'No beep at all - no power to board.',
      bios_speaker_vn: 'Không beep - board không có điện.',
    },
    beep_pattern: '... (silence)',
    diagram: 'psu',
    diagnosis_step: 1,
  },
  {
    id: 'no_display',
    title: 'No Display / Black Screen',
    title_vn: 'Không Có Hình Ảnh',
    description: 'PC turns on but monitor shows no signal.',
    description_vn: 'PC lên nguồn nhưng màn hình không tín hiệu.',
    symptoms: ['Fans spinning', 'LEDs on', 'No display output', 'No BIOS beep'],
    symptoms_vn: ['Quạt quay', 'Đèn sáng', 'Không có hình', 'Không tiếng beep'],
    correct_answer: 'ram_reseat',
    hints: ['Reseat RAM modules', 'Try one RAM stick', 'Check GPU seating', 'Clear CMOS'],
    hints_vn: ['Gắn lại RAM', 'Thử từng thanh RAM', 'Kiểm tra GPU', 'Clear CMOS'],
    difficulty: 'easy',
    icon: '🖥️',
    options: [
      { id: 'ram_reseat', label: 'Reseat RAM', label_vn: 'Gắn lại RAM', correct: true },
      { id: 'replace_cpu', label: 'Replace CPU', label_vn: 'Thay CPU' },
      { id: 'replace_monitor', label: 'Replace monitor', label_vn: 'Thay màn hình' },
      { id: 'reinstall_os', label: 'Reinstall Windows', label_vn: 'Cài lại Windows' },
    ],
    tool_hints: {
      multimeter: 'Voltages normal. PSU working correctly.',
      multimeter_vn: 'Điện áp bình thường. Nguồn tốt.',
      screwdriver: 'Reseating RAM fixed it - one stick was loose.',
      screwdriver_vn: 'Gắn lại RAM hết lỗi - một thanh bị lỏng.',
      compressed_air: 'RAM slots cleaned. Minor dust.',
      compressed_air_vn: 'Khe RAM đã vệ sinh. Bụi nhẹ.',
      spare_psu: 'Same issue with spare PSU.',
      spare_psu_vn: 'Vẫn lỗi với nguồn khác.',
      bios_speaker: 'Continuous long beep - RAM error.',
      bios_speaker_vn: 'Beep dài liên tục - lỗi RAM.',
    },
    beep_pattern: 'BEEP... BEEP... BEEP... (long repeating)',
    diagram: 'ram',
    diagnosis_step: 1,
  },
  {
    id: 'blue_screen',
    title: 'Blue Screen (CRITICAL_PROCESS_DIED)',
    title_vn: 'Màn Hình Xanh',
    description: 'PC blue-screens shortly after booting Windows.',
    description_vn: 'PC bị màn hình xanh sau khi vào Windows.',
    symptoms: ['BSOD on boot', 'CRITICAL_PROCESS_DIED', 'Boots to recovery', 'Safe mode crashes'],
    symptoms_vn: ['BSOD khi boot', 'Lỗi PROCESS_DIED', 'Vào recovery', 'Safe mode cũng lỗi'],
    correct_answer: 'repair_os',
    hints: ['Try Startup Repair', 'Check recent drivers', 'Run SFC /scannow', 'Reinstall Windows'],
    hints_vn: ['Thử Startup Repair', 'Kiểm tra driver', 'Chạy SFC /scannow', 'Cài lại Windows'],
    difficulty: 'medium',
    icon: '💀',
    options: [
      { id: 'repair_os', label: 'Corrupted system files', label_vn: 'File hệ thống hỏng', correct: true },
      { id: 'replace_ram', label: 'Replace RAM', label_vn: 'Thay RAM' },
      { id: 'replace_gpu', label: 'Replace GPU', label_vn: 'Thay GPU' },
      { id: 'replace_cpu', label: 'Replace CPU', label_vn: 'Thay CPU' },
    ],
    tool_hints: {
      multimeter: 'All voltages within spec.',
      multimeter_vn: 'Điện áp trong ngưỡng.',
      screwdriver: 'Hardware seated correctly.',
      screwdriver_vn: 'Phần cứng gắn chặt.',
      compressed_air: 'System clean, no overheating.',
      compressed_air_vn: 'Hệ thống sạch, không quá nhiệt.',
      spare_psu: 'BSOD still occurs with spare PSU.',
      spare_psu_vn: 'BSOD vẫn xảy ra với nguồn khác.',
      bios_speaker: 'Single short beep - POST OK, software issue.',
      bios_speaker_vn: 'Một beep ngắn - POST OK, lỗi phần mềm.',
    },
    beep_pattern: 'BEEP (single short - POST OK)',
    diagram: 'motherboard',
    diagnosis_step: 1,
  },
  {
    id: 'overheating',
    title: 'Overheating / Random Shutdowns',
    title_vn: 'Quá Nhiệt / Tắt Đột Ngột',
    description: 'PC randomly shuts down under load. Case feels hot.',
    description_vn: 'PC tắt đột ngột khi chạy nặng. Vỏ máy nóng.',
    symptoms: ['Random shutdowns', 'Loud fan then silence', 'Hot case', 'Crashes under load'],
    symptoms_vn: ['Tắt đột ngột', 'Quạt ồn rồi im', 'Vỏ nóng', 'Treo khi tải nặng'],
    correct_answer: 'cooler_issue',
    hints: ['Check CPU cooler', 'Reapply thermal paste', 'Check fan curves', 'Clean dust'],
    hints_vn: ['Kiểm tra tản nhiệt', 'Bôi keo tản nhiệt', 'Kiểm tra fan curve', 'Vệ sinh bụi'],
    difficulty: 'medium',
    icon: '🌡️',
    options: [
      { id: 'cooler_issue', label: 'Cooler failure / dust clogged', label_vn: 'Quạt CPU hỏng / bụi bít', correct: true },
      { id: 'psu_overload', label: 'PSU overload', label_vn: 'PSU quá tải' },
      { id: 'virus', label: 'Virus / malware', label_vn: 'Virus' },
      { id: 'ram_error', label: 'RAM error', label_vn: 'RAM lỗi' },
    ],
    tool_hints: {
      multimeter: 'PSU voltages fluctuate but in range.',
      multimeter_vn: 'Điện áp PSU dao động nhưng trong ngưỡng.',
      screwdriver: 'Cooler mounting screws loose. Heatsink not contacting.',
      screwdriver_vn: 'Ốc tản nhiệt lỏng. Không tiếp xúc đủ.',
      compressed_air: 'Heatsink fins clogged with dust. Blocked airflow.',
      compressed_air_vn: 'Khe tản nhiệt bị bụi bít. Không lưu thông khí.',
      spare_psu: 'Same shutdowns with spare PSU.',
      spare_psu_vn: 'Vẫn tắt với nguồn khác.',
      bios_speaker: 'Single short beep. BIOS overheat warning.',
      bios_speaker_vn: 'Một beep ngắn. BIOS báo quá nhiệt.',
    },
    beep_pattern: 'BEEP (short) + overheat LED',
    diagram: 'cpu_cooler',
    diagnosis_step: 2,
  },
  {
    id: 'gpu_artifacts',
    title: 'GPU Artifacts / Glitched Display',
    title_vn: 'Lỗi Hiển Thị GPU',
    description: 'Screen shows colored squares, lines, flickering.',
    description_vn: 'Màn hình có ô màu lạ, đường kẻ, nhấp nháy.',
    symptoms: ['Colored artifacts', 'Flickering', 'Lines across display', 'Driver crashes'],
    symptoms_vn: ['Ô màu lạ', 'Nhấp nháy', 'Đường kẻ', 'Driver crash'],
    correct_answer: 'gpu_dying',
    hints: ['Check GPU temps', 'Try underclocking', 'Test another monitor', 'Check GPU seating'],
    hints_vn: ['Kiểm tra nhiệt GPU', 'Thử underclock', 'Dùng màn khác', 'Kiểm tra gắn GPU'],
    difficulty: 'medium',
    icon: '🎮',
    options: [
      { id: 'gpu_dying', label: 'GPU failing / VRAM damaged', label_vn: 'GPU hỏng / VRAM lỗi', correct: true },
      { id: 'cable_loose', label: 'Loose display cable', label_vn: 'Dây màn hình lỏng' },
      { id: 'monitor_broken', label: 'Monitor broken', label_vn: 'Màn hình hỏng' },
      { id: 'driver_issue', label: 'Driver issue only', label_vn: 'Lỗi driver' },
    ],
    tool_hints: {
      multimeter: 'GPU power lines stable.',
      multimeter_vn: 'Đường điện GPU ổn định.',
      screwdriver: 'GPU seated firmly. Reseating did not help.',
      screwdriver_vn: 'GPU gắn chặt. Gắn lại không hết.',
      compressed_air: 'GPU fans clean. No overheating.',
      compressed_air_vn: 'Quạt GPU sạch. Không quá nhiệt.',
      spare_psu: 'Artifacts persist with spare PSU.',
      spare_psu_vn: 'Lỗi vẫn còn với nguồn khác.',
      bios_speaker: 'One short beep. Artifacts in BIOS - hardware fail.',
      bios_speaker_vn: 'Một beep. Lỗi ngay trong BIOS - phần cứng.',
    },
    beep_pattern: 'BEEP (short)',
    diagram: 'gpu',
    diagnosis_step: 2,
  },
  {
    id: 'slow_pc',
    title: 'Slow PC / 100% Disk Usage',
    title_vn: 'Máy Chậm / Disk 100%',
    description: 'PC extremely slow. Task Manager shows 100% disk usage.',
    description_vn: 'Máy rất chậm. Task Manager hiển thị disk 100%.',
    symptoms: ['100% disk usage', 'Slow boot', 'Apps freeze', 'Explorer hangs'],
    symptoms_vn: ['Disk 100%', 'Khởi động chậm', 'Ứng dụng đứng', 'Explorer treo'],
    correct_answer: 'hdd_failing',
    hints: ['Check Task Manager', 'Run CHKDSK', 'Check S.M.A.R.T.', 'Replace drive'],
    hints_vn: ['Kiểm tra Task Manager', 'Chạy CHKDSK', 'Kiểm tra S.M.A.R.T.', 'Thay ổ cứng'],
    difficulty: 'medium',
    icon: '🐌',
    options: [
      { id: 'hdd_failing', label: 'HDD failing / SSD full', label_vn: 'HDD hỏng / SSD đầy', correct: true },
      { id: 'virus', label: 'Virus infection', label_vn: 'Nhiễm virus' },
      { id: 'ram_low', label: 'Not enough RAM', label_vn: 'Thiếu RAM' },
      { id: 'cpu_old', label: 'CPU too old', label_vn: 'CPU cũ' },
    ],
    tool_hints: {
      multimeter: 'Drive power normal.',
      multimeter_vn: 'Nguồn ổ cứng bình thường.',
      screwdriver: 'Cables secure. Drive mounted properly.',
      screwdriver_vn: 'Cáp chặt. Ổ gắn đúng.',
      compressed_air: 'Drive clean and cool.',
      compressed_air_vn: 'Ổ sạch và mát.',
      spare_psu: 'Still slow with spare PSU.',
      spare_psu_vn: 'Vẫn chậm với nguồn khác.',
      bios_speaker: 'Single beep. BIOS detects drive with high latency.',
      bios_speaker_vn: 'Một beep. BIOS thấy ổ nhưng độ trễ cao.',
    },
    beep_pattern: 'BEEP (short)',
    diagram: 'storage',
    diagnosis_step: 2,
  },
  {
    id: 'no_boot_device',
    title: 'No Boot Device Found',
    title_vn: 'Không Tìm Thấy Ổ Khởi Động',
    description: 'Screen says "No boot device found" or "Reboot and Select proper Boot device".',
    description_vn: 'Màn hình báo "No boot device found".',
    symptoms: ['No boot device error', 'BIOS shows no drive', 'Was working yesterday'],
    symptoms_vn: ['Lỗi không boot device', 'BIOS không thấy ổ', 'Hôm qua còn chạy'],
    correct_answer: 'ssd_dead',
    hints: ['Check SATA/NVMe connections', 'Boot into BIOS', 'Try different SATA port', 'Check if drive appears'],
    hints_vn: ['Kiểm tra kết nối SATA', 'Vào BIOS', 'Thử cổng SATA khác', 'Kiểm tra BIOS thấy ổ không'],
    difficulty: 'easy',
    icon: '💿',
    options: [
      { id: 'ssd_dead', label: 'SSD disconnected or dead', label_vn: 'SSD mất kết nối hoặc chết', correct: true },
      { id: 'os_corrupt', label: 'Windows corrupted', label_vn: 'Windows hỏng' },
      { id: 'bios_bug', label: 'BIOS settings wrong', label_vn: 'Cài đặt BIOS sai' },
      { id: 'cable_loose', label: 'Loose SATA cable', label_vn: 'Cáp SATA lỏng' },
    ],
    tool_hints: {
      multimeter: 'SATA power correct voltage.',
      multimeter_vn: 'Cáp nguồn SATA đúng điện áp.',
      screwdriver: 'SSD not detected after reseating. Try known-working SSD.',
      screwdriver_vn: 'SSD không thấy dù đã gắn lại.',
      compressed_air: 'SATA ports cleaned.',
      compressed_air_vn: 'Cổng SATA đã vệ sinh.',
      spare_psu: 'Same with spare PSU.',
      spare_psu_vn: 'Vẫn lỗi với nguồn khác.',
      bios_speaker: 'Beep codes - missing storage device.',
      bios_speaker_vn: 'Mã beep báo thiếu thiết bị lưu trữ.',
    },
    beep_pattern: 'BEEP (short) + "No boot device"',
    diagram: 'storage',
    diagnosis_step: 1,
  },
  {
    id: 'boot_loop',
    title: 'Boot Loop / Continuous Restart',
    title_vn: 'Boot Loop / Khởi Động Liên Tục',
    description: 'PC turns on, shows BIOS splash, then restarts repeatedly.',
    description_vn: 'PC bật, thấy BIOS, rồi restart liên tục.',
    symptoms: ['Continuous restart loop', 'Never reaches desktop', 'Started after BIOS change'],
    symptoms_vn: ['Restart liên tục', 'Không vào desktop', 'Sau khi thay đổi BIOS'],
    correct_answer: 'bios_ram_instability',
    hints: ['Clear CMOS', 'Boot with one RAM stick', 'Check XMP stability', 'Update BIOS'],
    hints_vn: ['Clear CMOS', 'Boot 1 thanh RAM', 'Kiểm tra XMP', 'Cập nhật BIOS'],
    difficulty: 'hard',
    icon: '🔄',
    options: [
      { id: 'bios_ram_instability', label: 'Bad BIOS / RAM instability', label_vn: 'BIOS sai / RAM không ổn định', correct: true },
      { id: 'psu_failing', label: 'PSU failing under load', label_vn: 'Nguồn yếu' },
      { id: 'gpu_driver', label: 'GPU driver crash loop', label_vn: 'Driver GPU lỗi' },
      { id: 'windows_update', label: 'Corrupted Windows update', label_vn: 'Update Windows lỗi' },
    ],
    tool_hints: {
      multimeter: 'PSU voltages fluctuate during boot.',
      multimeter_vn: 'Điện áp PSU dao động khi boot.',
      screwdriver: 'Clearing CMOS resolved the boot loop.',
      screwdriver_vn: 'Clear CMOS đã khắc phục boot loop.',
      compressed_air: 'System clean.',
      compressed_air_vn: 'Hệ thống sạch.',
      spare_psu: 'Boot loop persists with spare PSU.',
      spare_psu_vn: 'Boot loop vẫn còn với nguồn khác.',
      bios_speaker: 'Repeating short beeps - memory/BIOS error.',
      bios_speaker_vn: 'Beep ngắn lặp lại - lỗi RAM/BIOS.',
    },
    beep_pattern: 'BEEP BEEP BEEP BEEP (continuous short)',
    diagram: 'motherboard',
    diagnosis_step: 3,
  },
  {
    id: 'strange_noise',
    title: 'Strange Noise from PC',
    title_vn: 'Âm Thanh Lạ Từ PC',
    description: 'PC makes grinding or clicking noise. Performance normal.',
    description_vn: 'PC phát tiếng lạ. Hiệu năng bình thường.',
    symptoms: ['Grinding noise', 'Buzzing from PSU area', 'Noise changes with load'],
    symptoms_vn: ['Tiếng lách cách', 'Ù từ nguồn', 'Ồn thay đổi theo tải'],
    correct_answer: 'fan_bearing',
    hints: ['Locate noise source', 'Stop fans one by one', 'Check HDD for clicks', 'Inspect fan blades'],
    hints_vn: ['Xác định vị trí ồn', 'Dừng từng quạt', 'Kiểm tra HDD', 'Kiểm tra cánh quạt'],
    difficulty: 'easy',
    icon: '🔊',
    options: [
      { id: 'fan_bearing', label: 'Fan bearing worn out', label_vn: 'Bạc quạt mòn', correct: true },
      { id: 'hdd_damage', label: 'HDD head crash', label_vn: 'HDD đầu đọc hỏng' },
      { id: 'coil_whine', label: 'GPU coil whine', label_vn: 'Cuộn cảm GPU kêu' },
      { id: 'loose_screw', label: 'Loose screw vibrating', label_vn: 'Ốc lỏng rung' },
    ],
    tool_hints: {
      multimeter: 'No electrical issues.',
      multimeter_vn: 'Không vấn đề điện.',
      screwdriver: 'Stopping CPU fan stops noise - bearing worn.',
      screwdriver_vn: 'Dừng quạt CPU hết ồn - bạc mòn.',
      compressed_air: 'Dust blow did not help.',
      compressed_air_vn: 'Xịt bụi không hết.',
      spare_psu: 'Noise persists.',
      spare_psu_vn: 'Ồn vẫn còn.',
      bios_speaker: 'No beep errors. POST fine.',
      bios_speaker_vn: 'Không lỗi beep. POST bình thường.',
    },
    beep_pattern: 'BEEP (short - normal)',
    diagram: 'fan',
    diagnosis_step: 1,
  },
  {
    id: 'no_wifi',
    title: 'Network Not Working / WiFi Missing',
    title_vn: 'Mất Mạng / Không Có WiFi',
    description: 'WiFi shows no networks. Ethernet works fine.',
    description_vn: 'WiFi không thấy mạng. Ethernet vẫn dùng được.',
    symptoms: ['No WiFi networks', 'Adapter missing in Device Manager', 'Driver error'],
    symptoms_vn: ['Không thấy WiFi', 'Thiếu adapter trong Device Manager', 'Lỗi driver'],
    correct_answer: 'wifi_driver',
    hints: ['Check WiFi enabled', 'Toggle Airplane mode', 'Check Device Manager', 'Reinstall driver'],
    hints_vn: ['Kiểm tra WiFi bật', 'Bật/tắt máy bay', 'Kiểm tra Device Manager', 'Cài lại driver'],
    difficulty: 'medium',
    icon: '📶',
    options: [
      { id: 'wifi_driver', label: 'WiFi driver / antenna issue', label_vn: 'Driver WiFi / antenna', correct: true },
      { id: 'router_down', label: 'Router down', label_vn: 'Router hỏng' },
      { id: 'isp_outage', label: 'ISP outage', label_vn: 'Mất internet ISP' },
      { id: 'windows_bug', label: 'Windows network bug', label_vn: 'Lỗi Windows' },
    ],
    tool_hints: {
      multimeter: 'WiFi card power correct.',
      multimeter_vn: 'Nguồn card WiFi đúng.',
      screwdriver: 'WiFi card seated. Antenna cable loose.',
      screwdriver_vn: 'Card gắn chặt. Cáp antenna lỏng.',
      compressed_air: 'Card cleaned. No damage.',
      compressed_air_vn: 'Đã vệ sinh. Không hư.',
      spare_psu: 'WiFi still missing.',
      spare_psu_vn: 'WiFi vẫn mất.',
      bios_speaker: 'POST OK. No hardware errors.',
      bios_speaker_vn: 'POST OK. Không lỗi phần cứng.',
    },
    beep_pattern: 'BEEP (short - normal)',
    diagram: 'wifi',
    diagnosis_step: 2,
  },
];
